# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: 'Name of the person'
      greet:
        required: false
        type: boolean
        default: true
        description: 'Whether to greet or not'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        if: ${{ inputs.greet }}
        run: echo "Hello, ${{ inputs.name }}!"

